version: '3.0'

services:
  database:
    image: mysql
    container_name: facebook
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'facebook'
    ports:
      - '3000:3306'
